config/routes.rb
Rails.application.routes.draw do

  root 'apps#index'

  get 'apps/search', to: 'apps#search'
  resources :apps, :only => [:index, :show] do
    member do
      resources :ratings, module: 'apps', as: 'app_ratings', param: :rating_id
      get '/privacy', to: 'apps#privacy', as: 'privacy'
      get '/icon', to: 'apps#icon', as: 'icon'
    end
  end

  resources :categories, :only => [:index, :show]

  get 'session', to: 'session#create'
  post 'session', to: 'session#store'
  delete 'session', to: 'session#destroy'
  get '/auth/:provider/callback', to: 'session#omniauth'

  namespace :manage do
    resources :apps
  end

  namespace :admin do

    resources :apps
    resources :categories
    resources :in_payloads do
        get 'to_app', to: 'in_payloads#to_app'
        post 'to_app', to: 'in_payloads#to_app'
    end
    resources :in_filter_rulesets
    resources :in_peers
    resources :out_peers
    resources :lti_consumers
    resources :users
    resources :sites

  end

  namespace :casa do

    get 'out/payloads', to: 'out#all'
    get 'out/payloads(/:originator_id)/:id', to: 'out#one'

    get 'local/payloads', to: 'local#all'
    get 'local/payloads/_elasticsearch', to: 'local#query'
    get 'local/payloads(/:originator_id)/:id', to: 'local#one'

  end

  post 'lti/launch', to: 'lti#launch'
  # Uncomment to allow an OAuth-ed LTI Launch via query parameters - handy for testing
  #get 'lti/launch', to: 'lti#launch'
  get 'lti/content_item/(:id)', to: 'lti#content_item'

  namespace :mobile do

    get 'cordova/launch', to: 'cordova#launch', as: 'cordova_launch'
    get 'cordova/exec/(:id)', to: 'cordova#exec', as: 'cordova_exec'

    get 'web_view_javascript_bridge/launch', to: 'web_view_javascript_bridge#launch', as: 'web_view_javascript_bridge_launch'
    get 'web_view_javascript_bridge/send/(:id)', to: 'web_view_javascript_bridge#_send', as: 'web_view_javascript_bridge_send'

  end

  get 'mobile', to: 'mobile#index'
  get 'mobile/privacy', to: 'mobile#privacy'
  get 'mobile/launch', to: 'mobile#launch'
  get 'mobile/return/(:id)', to: 'mobile#return'
  get 'mobile/abort', to: 'mobile#abort'

  # get 'status.json' is used by the rapporteur gem.

end

app/models/out_peer.rb
class OutPeer < ActiveRecord::Base
end

app/controllers/admin/out_peers_controller.rb
module Admin
  class OutPeersController < ApplicationController

    before_action :require_session_admin!

    def index

      @out_peers = OutPeer.all

    end

    def new

      @out_peer = OutPeer.new

    end

    def create

      @out_peer = OutPeer.new out_peer_params

      if @out_peer.save
        redirect_to [:admin, @out_peer]
      else
        render 'new'
      end

    end

    def show

      @out_peer = OutPeer.find params[:id]

    end

    def edit

      @out_peer = OutPeer.find params[:id]

    end

    def update

      @out_peer = OutPeer.find params[:id]

      if @out_peer.update out_peer_params
        redirect_to [:admin, @out_peer]
      else
        render 'edit'
      end

    end

    def destroy

      @out_peer = OutPeer.find params[:id]
      @out_peer.destroy

      redirect_to admin_out_peers_path

    end

  private

    def out_peer_params

      params.require(:out_peer).permit([
        :name,
        :address,
        :netmask,
        :secret
      ])

    end

  end
end

app/views/admin/out_peers/_form.html.erb
<%= form_for [:admin, @out_peer], :html => { :role => 'form' } do |f| %>

  <% if @out_peer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@out_peer.errors.count, "error") %> prohibited
      this peer from being saved:</h2>
    <ul>
    <% @out_peer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="form-field">
    <%= f.label :netmask, data: { help: 'If set, this property allows for specifyin an IP range. For example, if the address is 10.0.0.0, and the netmask is 255.0.0.0, then any requestor in the range 10.0.0.0 - 10.255.255.255 will be considered part of this out peer.' } %>
    <%= f.text_field :netmask %>
  </div>

  <div class="form-field">
    <%= f.label :secret, data: { help: 'If set, for a requestor to be qualified as this peer, it must sent the parameter "secret" with the value here when it requests apps from /casa/out/payloads or /casa/out/payloads/ORIGINATOR_ID/APP_ID.' } %>
    <%= f.text_field :secret %>
  </div>

  <p class="text-center">
    <%= f.submit 'Save Peer' %>
    <%= link_to 'Back without Saving',
                admin_out_peers_path,
                :class => 'button tertiary text-center',
                :role => 'button' %>
  </p>
<% end %>

app/views/admin/out_peers/edit.html.erb
<h1>Edit Outbound Peer</h1>

<%= render 'form' %>

app/views/admin/out_peers/index.html.erb
<h1>Outbound Peers</h1>

<p class="info">By default, apps with the &quot;Share&quot; will be shared to anyone who queries <%= link_to casa_out_payloads_url, casa_out_payloads_url %>; however, you can restrict an app to only be shared with some nodes by adding these nodes here and then marking the app to be shared as such by editing the &quot;Access Control&quot; section of the app's properties.</p>

<p><%= link_to 'Create New Outbound Peer',
            new_admin_out_peer_path,
            :class => 'button',
            :role => 'button' %></p>

<div style="overflow-x:scroll;">

  <table class="table" id="peers-list">

    <thead>
      <tr style="text-align:left;">
        <th>Name</th>
        <th>Address</th>
        <th>Netmask</th>
        <th>Secret</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @out_peers.each do |out_peer| %>
        <tr>
          <td><strong><%= out_peer.name %></strong></td>
          <td><strong><%= out_peer.address %></strong></td>
          <td><strong><%= out_peer.netmask %></strong></td>
          <td><%= out_peer.secret && out_peer.secret.length > 0 ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Show', admin_out_peer_path(out_peer) %></td>
          <td><%= link_to 'Edit', edit_admin_out_peer_path(out_peer) %></td>
          <td><%= link_to 'Destroy', admin_out_peer_path(out_peer),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

<script type="text/javascript">
  $('#peers-list').dataTable({
    "order": [[0, "asc"]]
  });
</script>

<p><%= link_to 'Create New Outbound Peer',
               new_admin_out_peer_path,
               :class => 'button',
               :role => 'button' %></p>

app/views/admin/out_peers/new.html.erb
<h1>New Outbound Peer</h1>

<%= render 'form' %>

app/views/admin/out_peers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @out_peer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @out_peer.address %>
</p>

<p>
  <strong>Netmask:</strong>
  <%= raw @out_peer.netmask && @out_peer.netmask.length > 0 ? @out_peer.netmask : '<em class="text-muted">None</em>' %>
</p>

<p>
  <strong>Secret:</strong>
  <%= raw @out_peer.secret && @out_peer.secret.length > 0 ? @out_peer.secret : '<em class="text-muted">None</em>' %>
</p>

<%= link_to 'Back', admin_out_peers_path %>
| <%= link_to 'Edit', edit_admin_out_peer_path(@out_peer) %>