config/routes.rb
Rails.application.routes.draw do

  root 'apps#index'

  get 'apps/search', to: 'apps#search'
  resources :apps, :only => [:index, :show] do
    member do
      resources :ratings, module: 'apps', as: 'app_ratings', param: :rating_id
      get '/privacy', to: 'apps#privacy', as: 'privacy'
      get '/icon', to: 'apps#icon', as: 'icon'
    end
  end

  resources :categories, :only => [:index, :show]

  get 'session', to: 'session#create'
  post 'session', to: 'session#store'
  delete 'session', to: 'session#destroy'
  get '/auth/:provider/callback', to: 'session#omniauth'

  namespace :manage do
    resources :apps
  end

  namespace :admin do

    resources :apps
    resources :categories
    resources :in_payloads do
        get 'to_app', to: 'in_payloads#to_app'
        post 'to_app', to: 'in_payloads#to_app'
    end
    resources :in_filter_rulesets
    resources :in_peers
    resources :out_peers
    resources :lti_consumers
    resources :users
    resources :sites

  end

  namespace :casa do

    get 'out/payloads', to: 'out#all'
    get 'out/payloads(/:originator_id)/:id', to: 'out#one'

    get 'local/payloads', to: 'local#all'
    get 'local/payloads/_elasticsearch', to: 'local#query'
    get 'local/payloads(/:originator_id)/:id', to: 'local#one'

  end

  post 'lti/launch', to: 'lti#launch'
  # Uncomment to allow an OAuth-ed LTI Launch via query parameters - handy for testing
  #get 'lti/launch', to: 'lti#launch'
  get 'lti/content_item/(:id)', to: 'lti#content_item'

  namespace :mobile do

    get 'cordova/launch', to: 'cordova#launch', as: 'cordova_launch'
    get 'cordova/exec/(:id)', to: 'cordova#exec', as: 'cordova_exec'

    get 'web_view_javascript_bridge/launch', to: 'web_view_javascript_bridge#launch', as: 'web_view_javascript_bridge_launch'
    get 'web_view_javascript_bridge/send/(:id)', to: 'web_view_javascript_bridge#_send', as: 'web_view_javascript_bridge_send'

  end

  get 'mobile', to: 'mobile#index'
  get 'mobile/privacy', to: 'mobile#privacy'
  get 'mobile/launch', to: 'mobile#launch'
  get 'mobile/return/(:id)', to: 'mobile#return'
  get 'mobile/abort', to: 'mobile#abort'

  # get 'status.json' is used by the rapporteur gem.

end

app/models/in_payload.rb
class InPayload < ActiveRecord::Base

  belongs_to :in_peer

  def content_data
    @content_data ||= JSON.parse content
  end

  def title
    title = nil
    if content_data['attributes'].has_key?('require')
      title = content_data['attributes']['require']['title']
    end
    if title == nil
      if content_data['attributes'].has_key?('use')
        title = content_data['attributes']['use']['title']
      end
    end
    if title == nil
      title = 'Untitled'
    end
    title
  end

  def related_app
    unless defined? @related_app
      @related_app = App.where(casa_id: casa_id, casa_originator_id: casa_originator_id).first
    end
    @related_app
  end

end

app/controllers/admin/in_payloads_controller.rb
module Admin
  class InPayloadsController < ApplicationController

    before_action :require_session_admin!

    def index

      @in_payloads = InPayload.where(app_id: nil, deleted_at: nil)

    end

    def show

      @in_payload = InPayload.find params[:id]
      @incomplete_payload = false
      
      attributes = @in_payload.content_data['attributes']

      if attributes.has_key?('use') and attributes['use'].has_key?('admin_contact')
        admin = attributes['use']['admin_contact']
        @incomplete_payload = true if admin['name'].to_s.empty? or admin['email'].to_s.empty?
      end

    end

    def to_app

      @in_payload = InPayload.find params[:in_payload_id]

      #TODO: add new attributes!

      attributes = @in_payload.content_data['attributes']
      attributes = attributes.merge(attributes['use']) if attributes.has_key?('use')
      attributes = attributes.merge(attributes['require']) if attributes.has_key?('require')

      # Map 'admin_contact' => 'primary_contact' if available.
      if attributes.has_key?('admin_contact') and attributes['admin_contact'].has_key?('name') and attributes['admin_contact'].has_key?('email')
        attributes['primary_contact_name'] = attributes['admin_contact']['name']
        attributes['primary_contact_email'] = attributes['admin_contact']['email']
      end

      # Map 'primary_contact' => user provided values.
      if params.has_key?('admin') and params['admin'].has_key?('name') and params['admin'].has_key?('email')
        attributes['primary_contact_name'] = params['admin']['name']
        attributes['primary_contact_email'] = params['admin']['email']
      end

      if @in_payload.related_app
        @app = @in_payload.related_app
      else
        @app = App.new
      end

      @app.title = attributes['title'] if attributes.has_key?('title')
      @app.uri = attributes['uri']
      @app.icon = attributes['icon'] if attributes.has_key?('icon')
      @app.description = attributes['description'] if attributes.has_key?('description')
      @app.enabled = true
      @app.share = attributes['share']
      @app.propagate = attributes['propagate']
      @app.updated_at = attributes['timestamp']
      @app.casa_id = @in_payload.casa_id
      @app.casa_originator_id = @in_payload.casa_originator_id
      @app.app_tags = attributes['tags'].map(){ |t| AppTag.new(name: t) } if attributes.has_key?('tags')
      @app.short_description = attributes['short_description'] if attributes.has_key?('short_description')
      @app.privacy_url = attributes['privacy_url'] if attributes.has_key?('privacy_url')
      @app.accessibility_url = attributes['accessibility_url'] if attributes.has_key?('accessibility_url')
      @app.vpat_url = attributes['vpat_url'] if attributes.has_key?('vpat_url')
      @app.acceptable = attributes['acceptable'].to_json if attributes.has_key?('acceptable')
      @app.primary_contact_name = attributes['primary_contact_name'] if attributes.has_key?('primary_contact_name')
      @app.primary_contact_email = attributes['primary_contact_email'] if attributes.has_key?('primary_contact_email')
      if attributes.has_key?('categories')
        @app.categories = attributes['categories'].map(){ |category_name|
          begin
            Category.where(name: category_name).first
          rescue
            nil
          end
        }.delete_if(){ |record|
          record.nil?
        }
      end

      unless attributes['lti'].blank?
        @app.lti = true
        @app.app_lti_configs = []

        # The LTI Attribute is allowed to be an object or an array in the CASA specification

        if attributes['lti'].is_a? Array
          attributes['lti'].each do |config_hash|
            @app.app_lti_configs << create_lti_config(config_hash)
          end
        else
          @app.app_lti_configs << create_lti_config(attributes['lti'])
        end
      end

      if attributes.include? 'ios_app'
        @app.ios_app_id = attributes['ios_app']['id'] if attributes['ios_app'].has_key?('id')
        @app.ios_app_scheme = attributes['ios_app']['scheme'] if attributes['ios_app'].has_key?('scheme')
        @app.ios_app_path = attributes['ios_app']['path'] if attributes['ios_app'].has_key?('path')
        @app.ios_app_affiliate_data = attributes['ios_app']['affiliate_data'] if attributes['ios_app'].has_key?('affiliate_data')
      end

      if attributes.include? 'android_app'
        @app.android_app_package = attributes['android_app']['package'] if attributes['android_app'].has_key?('package')
        @app.android_app_scheme = attributes['android_app']['scheme'] if attributes['android_app'].has_key?('scheme')
        @app.android_app_action = attributes['android_app']['action'] if attributes['android_app'].has_key?('action')
        @app.android_app_category = attributes['android_app']['category'] if attributes['android_app'].has_key?('category')
        @app.android_app_component = attributes['android_app']['component'] if attributes['android_app'].has_key?('component')
      end

      if attributes.include? 'author'
        @app.app_authors = []
        authors = attributes['author'].is_a?(Array) ? attributes['author'] : [attributes['author']]
        authors.each { |author| @app.app_authors << AppAuthor.new(author) }
      end

      if attributes.include? 'organization'
        @app.app_organizations = []
        organizations = attributes['organization'].is_a?(Array) ? attributes['organization'] : [attributes['organization']]
        organizations.each { |organization| @app.app_organizations << AppOrganization.new(organization) }
      end

      if attributes.include? 'privacy'
        privacy = {}
        attributes['privacy'].each do |classification, types|
          types.each do |type, level|
            if level == true
              level = 'true'
            elsif level == false
              level = 'false'
            else
              level = "\"#{level}\""
            end
            privacy["#{classification}_#{type}"] = level
          end
        end
        @app.app_privacy_policy = AppPrivacyPolicy.new(privacy)
      end

      if attributes.include? 'browser_features'
        attributes['browser_features'].each do |feature, level|
          unless level == 'none'
            @app.app_browser_features << AppBrowserFeature.new(feature: feature, level: level)
          end
        end
      end

      Rails.logger.info 'Creating a new app from an inbound payload.'

      @app.save
      @in_payload.update(app_id: @app.id)

      redirect_to @app

    end

    def destroy

      @in_payload = InPayload.find params[:id]
      @in_payload.update(deleted_at: Time.now)

      if params[:ignore]
        InPayloadIgnore.create casa_id: @in_payload.casa_id,
                               casa_originator_id: @in_payload.casa_originator_id
      end

      redirect_to admin_in_payloads_path

    end

    def create_lti_config(config_hash)
      AppLtiConfig.new do |c|
        c.lti_default = true
        c.lti_launch_url = config_hash['launch_url'] if config_hash.has_key?('launch_url')
        c.lti_launch_params = config_hash['launch_params'] if config_hash.has_key?('launch_params')
        c.lti_registration_url = config_hash['registration_url'] if config_hash.has_key?('registration_url')
        c.lti_configuration_url = config_hash['configuration_url'] if config_hash.has_key?('configuration_url')
        c.lti_content_item_message = config_hash['content_item_response'] if config_hash.has_key?('content_item_response')
        c.lti_lis_outcomes = config_hash['outcomes'] if config_hash.has_key?('outcomes')
        c.lti_version = config_hash['version'] if config_hash.has_key?('version')
        if config_hash.has_key?('ims_global_certification')
          c.lti_ims_global_registration_number = config_hash['ims_global_certification']['registration_number'] if config_hash['ims_global_certification'].has_key?('registration_number')
          c.lti_ims_global_conformance_date = config_hash['ims_global_certification']['conformance_date'] if config_hash['ims_global_certification'].has_key?('conformance_date')
          c.lti_ims_global_registration_link = config_hash['ims_global_certification']['link'] if config_hash['ims_global_certification'].has_key?('link')
        end
      end
    end

  end

end

app/views/admin/in_payloads/index.html.erb
<h1>Pending Apps</h1>

<p class="info">This is a queue of apps (both new apps, and updates to existing apps in the store) that have been discovered by querying peers. You can click &quot;Manage&quot; to approve or reject an app in this queue, and you can add or remove peers apps are discovered from by going to <%= link_to 'ADMIN > IN PEERS', admin_in_peers_url, target: '_blank' %>. You can also configure filter rules to avoid apps from being added to this queue by going to <%= link_to 'ADMIN > IN FILTER RULESETS', admin_in_filter_rulesets_url, target: '_blank' %>.</p>

<div style="overflow-x:scroll;">

  <table class="table" id="in_payload-list">

    <thead>
      <tr style="text-align:left">
        <th style="white-space: nowrap;">Title</th>
        <th style="white-space: nowrap;">Sender</th>
        <th style="white-space: nowrap;">CASA Identifier</th>
        <th style="white-space: nowrap;">Related App</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @in_payloads.each do |in_payload| %>
        <tr>
          <td><%= in_payload.title %></td>
          <td><%= in_payload.in_peer ? in_payload.in_peer.name : raw('<em>Removed</em>') %></td>
          <td><%= in_payload.casa_id %>@<%= in_payload.casa_originator_id %></td>
          <td><%= in_payload.related_app ? in_payload.related_app.title : raw('<em>New</em>') %></td>
          <td><%= link_to 'Manage', admin_in_payload_url(in_payload) %></td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

<script type="text/javascript">
  $('#in_payload-list').dataTable({
    "order": [[0, "asc"]]
  });
</script>

app/views/admin/in_payloads/show.html.erb
<h2><%= @in_payload.related_app ? 'Update' : 'Create' %> App</h2>

<p><strong>CASA Identity</strong></p>

<pre style="border: 1px solid #bbb; padding: 10px;"><%= @in_payload.content_data['identity'].to_yaml.sub('---', '') %></pre>

<p><strong><%= @in_payload.related_app ? 'Update' : 'Creation' %> Content</strong></p>

<pre style="border: 1px solid #bbb; padding: 10px;"><%= @in_payload.content_data['attributes'].to_yaml.sub('---', '') %></pre>

<% if @incomplete_payload %>

  <%= form_tag admin_in_payload_to_app_url(@in_payload), :method => 'post' do %>
    <%= field_set_tag "Update required admin contact fields" do %>
      <%= label :admin, :name, "Name" %>
      <%= text_field_tag 'admin[name]', nil, :required => true %>
      <%= label :admin, :email, "Email" %>
      <%= email_field 'admin[email]' , nil, :required => true, pattern: ".{5,}" %>
      <%= submit_tag("Approve (and update missing required fields)") %>
    <% end %>
  
  <% end %>

<% else %>
  <%= link_to "Approve (#{@in_payload.related_app ? 'Update Existing App' : 'Create New App'})", admin_in_payload_to_app_url(@in_payload), class: 'button approve' %>
<% end %>

<%= link_to 'Ignore This Payload', admin_in_payload_url(@in_payload), method: :delete, class: 'button warning' %>

<%= link_to 'Ignore This App', admin_in_payload_url(@in_payload, ignore: true), method: :delete, class: 'button danger ignore' %>

<%= link_to 'Back without Saving', admin_in_payloads_path, class: 'button tertiary' %>

<script type="text/javascript">
  $('.button.ignore').click(function(e){
    return confirm('Are you sure you wish to ignore this app? No future updates received for this app will be stored in your queue.');
  })
</script>