config/routes.rb
Rails.application.routes.draw do

  root 'apps#index'

  get 'apps/search', to: 'apps#search'
  resources :apps, :only => [:index, :show] do
    member do
      resources :ratings, module: 'apps', as: 'app_ratings', param: :rating_id
      get '/privacy', to: 'apps#privacy', as: 'privacy'
      get '/icon', to: 'apps#icon', as: 'icon'
    end
  end

  resources :categories, :only => [:index, :show]

  get 'session', to: 'session#create'
  post 'session', to: 'session#store'
  delete 'session', to: 'session#destroy'
  get '/auth/:provider/callback', to: 'session#omniauth'

  namespace :manage do
    resources :apps
  end

  namespace :admin do

    resources :apps
    resources :categories
    resources :in_payloads do
        get 'to_app', to: 'in_payloads#to_app'
        post 'to_app', to: 'in_payloads#to_app'
    end
    resources :in_filter_rulesets
    resources :in_peers
    resources :out_peers
    resources :lti_consumers
    resources :users
    resources :sites

  end

  namespace :casa do

    get 'out/payloads', to: 'out#all'
    get 'out/payloads(/:originator_id)/:id', to: 'out#one'

    get 'local/payloads', to: 'local#all'
    get 'local/payloads/_elasticsearch', to: 'local#query'
    get 'local/payloads(/:originator_id)/:id', to: 'local#one'

  end

  post 'lti/launch', to: 'lti#launch'
  # Uncomment to allow an OAuth-ed LTI Launch via query parameters - handy for testing
  #get 'lti/launch', to: 'lti#launch'
  get 'lti/content_item/(:id)', to: 'lti#content_item'

  namespace :mobile do

    get 'cordova/launch', to: 'cordova#launch', as: 'cordova_launch'
    get 'cordova/exec/(:id)', to: 'cordova#exec', as: 'cordova_exec'

    get 'web_view_javascript_bridge/launch', to: 'web_view_javascript_bridge#launch', as: 'web_view_javascript_bridge_launch'
    get 'web_view_javascript_bridge/send/(:id)', to: 'web_view_javascript_bridge#_send', as: 'web_view_javascript_bridge_send'

  end

  get 'mobile', to: 'mobile#index'
  get 'mobile/privacy', to: 'mobile#privacy'
  get 'mobile/launch', to: 'mobile#launch'
  get 'mobile/return/(:id)', to: 'mobile#return'
  get 'mobile/abort', to: 'mobile#abort'

  # get 'status.json' is used by the rapporteur gem.

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :apps

  validates :name,
    presence: true,
    length: { minimum: 1 }

  def has_apps?
    self.apps.size > 0
  end

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController

    before_action :require_session_admin!

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new category_params
      @category.app_ids = params[:category][:apps]
      if @category.save
        redirect_to category_url @category
      else
        render 'new'
      end
    end

    def edit
      @category = Category.find params[:id]
      @apps = App.all
    end

    def update
      @category = Category.find params[:id]
      @category.app_ids = params[:category][:apps]
      if @category.update category_params
        redirect_to category_url @category
      else
        render 'edit'
      end
    end

    def destroy
      @category = Category.find params[:id]
      @category.destroy
      redirect_to admin_categories_path
    end

  private

    def category_params
      params.require(:category).permit([
        :name
      ])
    end

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show

    @category = Category.find params[:id]
    @apps = @category.apps.available_to_launch_method(launch_provider.get)

    @apps.each { |app| event.found app }

  end

end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], :html => { :role => 'form' } do |f| %>

  <% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <% if @apps %>
      <div class="form-field">
        <%= f.label :apps %>
        <%= f.select :apps, @apps.map(){ |a|
          [a.title, a.id, {:selected => @category.apps.include?(a)}]
        }, {}, {:multiple => true} %>
      </div>
  <% end %>

  <p class="text-center">
    <%= f.submit 'Save Category' %>
    <%= link_to 'Back without Saving',
                admin_categories_path,
                :class => 'button tertiary text-center',
                :role => 'button' %>
  </p>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>

<p class="info">Categories are used to cluster groups of apps together. If you define the categories <%= raw AppsController::DEFAULT_CATEGORIES.map(){ |c| "&quot;#{c}&quot;" }.to_sentence %>, the apps in these categories will be shown on the home screen. These categories, and any other you define, will also show up in the menu under the CATEGORIES section.</p>

<p><%= link_to 'Create New Category',
               new_admin_category_path,
               :class => 'button',
               :role => 'button' %></p>

<div>

  <table class="table" id="categories-list">

    <thead>
      <tr>
        <th style="text-align:left;">Name</th>
        <th>Apps</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><strong><%= category.name %></strong></td>
          <td class="text-center"><%= category.apps.count %></td>
          <td><%= link_to 'Show', category_path(category) %></td>
          <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
          <td><%= link_to 'Destroy', admin_category_path(category),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

<script type="text/javascript">
  $('#categories-list').dataTable({
    "order": [[0, "asc"]]
  });
</script>

<p><%= link_to 'Create New Category',
               new_admin_category_path,
               :class => 'button',
               :role => 'button' %></p>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>