config/routes.rb
Rails.application.routes.draw do

  root 'apps#index'

  get 'apps/search', to: 'apps#search'
  resources :apps, :only => [:index, :show] do
    member do
      resources :ratings, module: 'apps', as: 'app_ratings', param: :rating_id
      get '/privacy', to: 'apps#privacy', as: 'privacy'
      get '/icon', to: 'apps#icon', as: 'icon'
    end
  end

  resources :categories, :only => [:index, :show]

  get 'session', to: 'session#create'
  post 'session', to: 'session#store'
  delete 'session', to: 'session#destroy'
  get '/auth/:provider/callback', to: 'session#omniauth'

  namespace :manage do
    resources :apps
  end

  namespace :admin do

    resources :apps
    resources :categories
    resources :in_payloads do
        get 'to_app', to: 'in_payloads#to_app'
        post 'to_app', to: 'in_payloads#to_app'
    end
    resources :in_filter_rulesets
    resources :in_peers
    resources :out_peers
    resources :lti_consumers
    resources :users
    resources :sites

  end

  namespace :casa do

    get 'out/payloads', to: 'out#all'
    get 'out/payloads(/:originator_id)/:id', to: 'out#one'

    get 'local/payloads', to: 'local#all'
    get 'local/payloads/_elasticsearch', to: 'local#query'
    get 'local/payloads(/:originator_id)/:id', to: 'local#one'

  end

  post 'lti/launch', to: 'lti#launch'
  # Uncomment to allow an OAuth-ed LTI Launch via query parameters - handy for testing
  #get 'lti/launch', to: 'lti#launch'
  get 'lti/content_item/(:id)', to: 'lti#content_item'

  namespace :mobile do

    get 'cordova/launch', to: 'cordova#launch', as: 'cordova_launch'
    get 'cordova/exec/(:id)', to: 'cordova#exec', as: 'cordova_exec'

    get 'web_view_javascript_bridge/launch', to: 'web_view_javascript_bridge#launch', as: 'web_view_javascript_bridge_launch'
    get 'web_view_javascript_bridge/send/(:id)', to: 'web_view_javascript_bridge#_send', as: 'web_view_javascript_bridge_send'

  end

  get 'mobile', to: 'mobile#index'
  get 'mobile/privacy', to: 'mobile#privacy'
  get 'mobile/launch', to: 'mobile#launch'
  get 'mobile/return/(:id)', to: 'mobile#return'
  get 'mobile/abort', to: 'mobile#abort'

  # get 'status.json' is used by the rapporteur gem.

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :apps

  validates :name,
    presence: true,
    length: { minimum: 1 }

  def has_apps?
    self.apps.size > 0
  end

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController

    before_action :require_session_admin!

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new category_params
      @category.app_ids = params[:category][:apps]
      if @category.save
        redirect_to category_url @category
      else
        render 'new'
      end
    end

    def edit
      @category = Category.find params[:id]
      @apps = App.all
    end

    def update
      @category = Category.find params[:id]
      @category.app_ids = params[:category][:apps]
      if @category.update category_params
        redirect_to category_url @category
      else
        render 'edit'
      end
    end

    def destroy
      @category = Category.find params[:id]
      @category.destroy
      redirect_to admin_categories_path
    end

  private

    def category_params
      params.require(:category).permit([
        :name
      ])
    end

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show

    @category = Category.find params[:id]
    @apps = @category.apps.available_to_launch_method(launch_provider.get)

    @apps.each { |app| event.found app }

  end

end

app/views/categories/_menu.html.erb
<%= form_tag categories_url, :class => 'select-navigation' do |f| %>
  <% select_tag :category_id,
                options_for_select(Category.order(name: :asc).map(){ |a| [a.name, a.id] }.prepend(['-- Browse Category --', '0']), @category.id),
                {'class' => 'form-control'} %>
<% end %>
<script type="text/javascript">
  $('.select-navigation select').val(0)
  $('.select-navigation select').change(function(){
    window.location = $(this).closest('form').attr('action') + '/' + $(this).val();
  })
</script>

app/views/categories/show.html.erb
<%= render 'categories/menu' %>

<nav class="collection">
  <header>
    <h3><%= @category.name %></h3>
  </header>
  <ul class="clearfix list-unstyled">
    <% @apps.where(enabled: true).each do |app| %><li <% if app.official %>class="official"<% end %>>
        <a href="<%= url_for app %>">
          <figure>
            <%= app.icon_tag %>
            <figcaption>
              <h4><%= app.title %></h4>
              <p><%= app.description %></p>
              <div class="stars">
                <% unless app.average_rating.nan? %>
                  <span class="filled"><%= raw (1..app.average_rating.round(0)).map { '&#9733;' }.join ' ' %></span>
                  <span class="unfilled"><%= raw (app.average_rating.round(0)+1..5).map { '&#9734;' }.join ' ' %></span>
                <% else %>
                  <span class="none"><%= raw (1..5).map { '&#9734;' }.join ' ' %></span>
                <% end %>
              </div>
            </figcaption>
          </figure>
        </a>
      </li><% end %>
  </ul>
</nav>


<% if session_user and session_user.admin %>
<p>
  <%= link_to 'Edit', edit_admin_category_url(@category), class: 'button success' %>
  <%= link_to 'Destroy', admin_category_path(@category),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this category?" },
            class: 'button danger' %>
</p>
<% end %>